apiVersion: v2
name: no-01-prefix-root
description: Controlled no_01 Dependabot Helm path-prefix fixture
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: no01-victim-chart
    version: 1.0.0
    repository: https://pbzqf-89-37-63-107.run.pinggy-free.link/victim
  - name: no01-attacker-chart
    version: 1.0.0
    repository: https://pbzqf-89-37-63-107.run.pinggy-free.link/victim-attacker
